import type { ChannelDefinition } from "./types.js";

/** 注入到渠道页的 fill + submit 脚本（避免模板字符串转义坑，用数组拼接） */
export function buildFillAndSubmitScript(
  channel: ChannelDefinition,
  prompt: string,
): string {
  const lines = [
    "(async function () {",
    `  const channel = ${JSON.stringify(channel)};`,
    `  const prompt = ${JSON.stringify(prompt)};`,
    "",
    "  function sleep(ms) {",
    "    return new Promise(function (r) { setTimeout(r, ms); });",
    "  }",
    "",
    "  function matchPatternToRegExp(pattern) {",
    "    var escaped = pattern.replace(/[.+^${}()|[\\]\\\\]/g, '\\\\$&').replace(/\\*/g, '.*');",
    "    return new RegExp('^' + escaped + '$');",
    "  }",
    "",
    "  function isVisible(el) {",
    "    if (!el.getClientRects().length) return false;",
    "    var style = window.getComputedStyle(el);",
    "    if (style.visibility === 'hidden' || style.display === 'none' || style.opacity === '0') return false;",
    "    var rect = el.getBoundingClientRect();",
    "    return rect.width > 0 && rect.height > 0;",
    "  }",
    "",
    "  function findBySelectors(selectors, opts) {",
    "    opts = opts || {};",
    "    for (var i = 0; i < selectors.length; i++) {",
    "      var nodes;",
    "      try { nodes = document.querySelectorAll(selectors[i]); } catch (e) { continue; }",
    "      for (var j = 0; j < nodes.length; j++) {",
    "        var node = nodes[j];",
    "        if (!(node instanceof HTMLElement)) continue;",
    "        if (!isVisible(node)) continue;",
    "        if (!opts.allowDisabled && (node.hasAttribute('disabled') || node.getAttribute('aria-disabled') === 'true' || node.getAttribute('data-disabled') === 'true')) continue;",
    "        return node;",
    "      }",
    "    }",
    "    return null;",
    "  }",
    "",
    "  function waitForSelectors(selectors, maxMs, opts) {",
    "    var max = maxMs || 12000;",
    "    var start = Date.now();",
    "    return new Promise(function (resolve, reject) {",
    "      var done = false;",
    "      var obs;",
    "      var timer;",
    "      function finish(fn, value) {",
    "        if (done) return;",
    "        done = true;",
    "        if (timer) clearInterval(timer);",
    "        if (obs) obs.disconnect();",
    "        fn(value);",
    "      }",
    "      function tryOnce() {",
    "        var t = findBySelectors(selectors, opts);",
    "        if (t) { finish(resolve, t); return; }",
    "        if (Date.now() - start >= max) {",
    "          finish(reject, new Error('timeout waiting for element: ' + selectors.join(' | ')));",
    "        }",
    "      }",
    "      obs = new MutationObserver(tryOnce);",
    "      obs.observe(document.documentElement, { childList: true, subtree: true, attributes: true });",
    "      timer = setInterval(tryOnce, 200);",
    "      tryOnce();",
    "    });",
    "  }",
    "",
    "  function setNativeValue(el, value) {",
    "    var proto = el instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype;",
    "    var desc = Object.getOwnPropertyDescriptor(proto, 'value');",
    "    var setter = desc && desc.set;",
    "    el.focus();",
    "    if (setter) setter.call(el, ''); else el.value = '';",
    "    if (setter) setter.call(el, value); else el.value = value;",
    "    // 只派发一次 input，避免框架把 data 再追加一遍导致重复",
    "    el.dispatchEvent(new Event('input', { bubbles: true }));",
    "    el.dispatchEvent(new Event('change', { bubbles: true }));",
    "  }",
    "",
    "  function fillContentEditable(el, text) {",
    "    el.focus();",
    "    try {",
    "      var selection = window.getSelection();",
    "      var range = document.createRange();",
    "      range.selectNodeContents(el);",
    "      selection.removeAllRanges();",
    "      selection.addRange(range);",
    "    } catch (e) {}",
    "    try { document.execCommand('selectAll', false); } catch (e1) {}",
    "    try { document.execCommand('delete', false); } catch (e2) {}",
    "    // Lexical / 现代编辑器优先走 insertText",
    "    var ok = false;",
    "    try { ok = document.execCommand('insertText', false, text); } catch (e3) { ok = false; }",
    "    var current = (el.innerText || el.textContent || '').trim();",
    "    if (!ok || !current) {",
    "      try {",
    "        var dt = new DataTransfer();",
    "        dt.setData('text/plain', text);",
    "        el.dispatchEvent(new ClipboardEvent('paste', { clipboardData: dt, bubbles: true, cancelable: true }));",
    "      } catch (e4) {}",
    "      current = (el.innerText || el.textContent || '').trim();",
    "    }",
    "    if (!current) {",
    "      // 最后兜底：直接写 DOM + input（部分站点仅展示用）",
    "      el.textContent = text;",
    "      el.dispatchEvent(new Event('input', { bubbles: true }));",
    "    }",
    "  }",
    "",
    "  function fillElement(el, kind, text) {",
    "    el.focus();",
    "    if (kind === 'contenteditable' || el.isContentEditable || el.getAttribute('contenteditable') === 'true' || el.getAttribute('data-lexical-editor') === 'true') {",
    "      fillContentEditable(el, text);",
    "      return;",
    "    }",
    "    if (el instanceof HTMLTextAreaElement || el instanceof HTMLInputElement) {",
    "      setNativeValue(el, text);",
    "      return;",
    "    }",
    "    throw new Error('unsupported fill target');",
    "  }",
    "",
    "  function pressEnter(el) {",
    "    el.focus();",
    "    var opts = { key: 'Enter', code: 'Enter', keyCode: 13, which: 13, bubbles: true, cancelable: true };",
    "    el.dispatchEvent(new KeyboardEvent('keydown', opts));",
    "    el.dispatchEvent(new KeyboardEvent('keypress', opts));",
    "    el.dispatchEvent(new KeyboardEvent('keyup', opts));",
    "  }",
    "",
    "  function findByButtonText(texts) {",
    "    var nodes = document.querySelectorAll('button, input[type=\"submit\"], input[type=\"button\"], [role=\"button\"], div, span');",
    "    for (var i = 0; i < nodes.length; i++) {",
    "      var el = nodes[i];",
    "      if (!(el instanceof HTMLElement) || !isVisible(el)) continue;",
    "      if (el.hasAttribute('disabled') || el.getAttribute('aria-disabled') === 'true') continue;",
    "      var label = ((el.getAttribute('aria-label') || '') + ' ' + (el.value || '') + ' ' + (el.textContent || '')).trim();",
    "      for (var j = 0; j < texts.length; j++) {",
    "        if (label === texts[j] || label.indexOf(texts[j]) !== -1) return el;",
    "      }",
    "    }",
    "    return null;",
    "  }",
    "",
    "  function inputLooksSubmitted(inputEl, promptText) {",
    "    if (!inputEl) return false;",
    "    var expected = (promptText || '').trim();",
    "    if (!expected) return false;",
    "    if (inputEl instanceof HTMLTextAreaElement || inputEl instanceof HTMLInputElement) {",
    "      var v = (inputEl.value || '').trim();",
    "      return v.length === 0 || v !== expected;",
    "    }",
    "    if (inputEl.isContentEditable || inputEl.getAttribute('contenteditable') === 'true') {",
    "      var t = (inputEl.innerText || inputEl.textContent || '').trim();",
    "      return t.length === 0 || t !== expected;",
    "    }",
    "    return false;",
    "  }",
    "",
    "  async function doSubmit(inputEl, submit, promptText) {",
    "    await sleep(450);",
    "    var clickSelectors = submit.selectors || [];",
    "    if ((submit.kind === 'click' || clickSelectors.length) && clickSelectors.length) {",
    "      try {",
    "        var btn = await waitForSelectors(clickSelectors, 3500, { allowDisabled: false });",
    "        btn.click();",
    "        await sleep(400);",
    "        if (inputLooksSubmitted(inputEl, promptText)) return;",
    "        return;",
    "      } catch (e) {}",
    "    }",
    "    var byText = findByButtonText(['发送消息', '百度一下', '发送', 'Search', 'Google 搜索', 'Send']);",
    "    if (byText) {",
    "      byText.click();",
    "      await sleep(400);",
    "      if (inputLooksSubmitted(inputEl, promptText)) return;",
    "      return;",
    "    }",
    "    if (submit.kind === 'form' || submit.formSelectors) {",
    "      var formSel = submit.formSelectors || ['form'];",
    "      var form = findBySelectors(formSel);",
    "      if (!form && inputEl.closest) form = inputEl.closest('form');",
    "      if (form instanceof HTMLFormElement) {",
    "        if (typeof form.requestSubmit === 'function') form.requestSubmit();",
    "        else form.submit();",
    "        await sleep(400);",
    "        if (inputLooksSubmitted(inputEl, promptText)) return;",
    "        return;",
    "      }",
    "    }",
    "    pressEnter(inputEl);",
    "    await sleep(500);",
    "    if (inputLooksSubmitted(inputEl, promptText)) return;",
    "    var fallback = [",
    "      '.send-button-container',",
    "      'button[data-testid*=\"send\"]',",
    "      'button[class*=\"send\"]',",
    "      'input[name=\"btnK\"]', 'button[name=\"btnK\"]',",
    "      'input[type=\"submit\"]', '#su',",
    "      'button[aria-label*=\"Search\"]', 'button[aria-label*=\"搜索\"]',",
    "      'button[aria-label*=\"Send\"]', 'button[aria-label*=\"发送\"]'",
    "    ].concat(clickSelectors);",
    "    var fb = findBySelectors(fallback);",
    "    if (fb) {",
    "      fb.click();",
    "      await sleep(400);",
    "      if (inputLooksSubmitted(inputEl, promptText)) return;",
    "      return;",
    "    }",
    "    if (submit.kind === 'enter') return;",
    "    if (inputLooksSubmitted(inputEl, promptText)) return;",
    "    if (submit.kind === 'click') throw new Error('submit button not found / not enabled');",
    "  }",
    "",
    "  var hostOk = channel.matches.some(function (p) { return matchPatternToRegExp(p).test(location.href); });",
    "  if (!hostOk) throw new Error('page URL does not match channel: ' + location.href);",
    "",
    "  var input = await waitForSelectors(channel.fill.selectors, channel.fill.waitMs || 12000);",
    "  fillElement(input, channel.fill.kind, prompt);",
    "  await doSubmit(input, channel.submit, prompt);",
    "  return { ok: true };",
    "})()",
  ];
  return lines.join("\n");
}

/** 聚焦并清空输入框（配合 Electron insertText，适配 Slate/Lexical） */
export function buildFocusClearScript(channel: ChannelDefinition): string {
  const channelJson = JSON.stringify(channel);
  return [
    "(async function () {",
    `  var channel = ${channelJson};`,
    "  function isVisible(el) {",
    "    if (!el.getClientRects().length) return false;",
    "    var style = window.getComputedStyle(el);",
    "    return style.visibility !== 'hidden' && style.display !== 'none';",
    "  }",
    "  function findBySelectors(selectors) {",
    "    for (var i = 0; i < selectors.length; i++) {",
    "      var nodes;",
    "      try { nodes = document.querySelectorAll(selectors[i]); } catch (e) { continue; }",
    "      for (var j = 0; j < nodes.length; j++) {",
    "        var node = nodes[j];",
    "        if (!(node instanceof HTMLElement) || !isVisible(node)) continue;",
    "        return node;",
    "      }",
    "    }",
    "    return null;",
    "  }",
    "  function waitForSelectors(selectors, maxMs) {",
    "    var max = maxMs || 12000;",
    "    var start = Date.now();",
    "    return new Promise(function (resolve, reject) {",
    "      var done = false;",
    "      var obs;",
    "      var timer;",
    "      function finish(fn, v) { if (done) return; done = true; if (timer) clearInterval(timer); if (obs) obs.disconnect(); fn(v); }",
    "      function tryOnce() {",
    "        var t = findBySelectors(selectors);",
    "        if (t) { finish(resolve, t); return; }",
    "        if (Date.now() - start >= max) finish(reject, new Error('timeout waiting for input'));",
    "      }",
    "      obs = new MutationObserver(tryOnce);",
    "      obs.observe(document.documentElement, { childList: true, subtree: true, attributes: true });",
    "      timer = setInterval(tryOnce, 200);",
    "      tryOnce();",
    "    });",
    "  }",
    "  var input = await waitForSelectors(channel.fill.selectors, channel.fill.waitMs || 12000);",
    "  input.focus();",
    "  try {",
    "    var sel = window.getSelection();",
    "    var range = document.createRange();",
    "    range.selectNodeContents(input);",
    "    sel.removeAllRanges();",
    "    sel.addRange(range);",
    "  } catch (e) {}",
    "  try { document.execCommand('selectAll', false); } catch (e1) {}",
    "  try { document.execCommand('delete', false); } catch (e2) {}",
    "  if (input instanceof HTMLTextAreaElement || input instanceof HTMLInputElement) {",
    "    var proto = input instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype;",
    "    var desc = Object.getOwnPropertyDescriptor(proto, 'value');",
    "    if (desc && desc.set) desc.set.call(input, ''); else input.value = '';",
    "    input.dispatchEvent(new Event('input', { bubbles: true }));",
    "  }",
    "  input.focus();",
    "  return { ok: true };",
    "})()",
  ].join("\n");
}

/** 仅执行发送（输入已由 insertText 完成） */
export function buildSubmitOnlyScript(channel: ChannelDefinition): string {
  const channelJson = JSON.stringify(channel);
  return [
    "(async function () {",
    `  var channel = ${channelJson};`,
    "  function sleep(ms) { return new Promise(function (r) { setTimeout(r, ms); }); }",
    "  function isVisible(el) {",
    "    if (!el.getClientRects().length) return false;",
    "    var style = window.getComputedStyle(el);",
    "    return style.visibility !== 'hidden' && style.display !== 'none';",
    "  }",
    "  function findBySelectors(selectors) {",
    "    for (var i = 0; i < selectors.length; i++) {",
    "      var nodes;",
    "      try { nodes = document.querySelectorAll(selectors[i]); } catch (e) { continue; }",
    "      for (var j = 0; j < nodes.length; j++) {",
    "        var node = nodes[j];",
    "        if (!(node instanceof HTMLElement) || !isVisible(node)) continue;",
    "        if (node.hasAttribute('disabled') || node.getAttribute('aria-disabled') === 'true') continue;",
    "        return node;",
    "      }",
    "    }",
    "    return null;",
    "  }",
    "  function waitForSelectors(selectors, maxMs) {",
    "    var max = maxMs || 8000;",
    "    var start = Date.now();",
    "    return new Promise(function (resolve, reject) {",
    "      var done = false;",
    "      var obs;",
    "      var timer;",
    "      function finish(fn, v) { if (done) return; done = true; if (timer) clearInterval(timer); if (obs) obs.disconnect(); fn(v); }",
    "      function tryOnce() {",
    "        var t = findBySelectors(selectors);",
    "        if (t) { finish(resolve, t); return; }",
    "        if (Date.now() - start >= max) finish(reject, new Error('timeout waiting for submit'));",
    "      }",
    "      obs = new MutationObserver(tryOnce);",
    "      obs.observe(document.documentElement, { childList: true, subtree: true, attributes: true });",
    "      timer = setInterval(tryOnce, 150);",
    "      tryOnce();",
    "    });",
    "  }",
    "  function pressEnter(el) {",
    "    if (!el) return;",
    "    el.focus();",
    "    var opts = { key: 'Enter', code: 'Enter', keyCode: 13, which: 13, bubbles: true, cancelable: true };",
    "    el.dispatchEvent(new KeyboardEvent('keydown', opts));",
    "    el.dispatchEvent(new KeyboardEvent('keypress', opts));",
    "    el.dispatchEvent(new KeyboardEvent('keyup', opts));",
    "  }",
    "  await sleep(350);",
    "  var clickSelectors = channel.submit.selectors || [];",
    "  var input = findBySelectors(channel.fill.selectors);",
    "  if (clickSelectors.length) {",
    "    try {",
    "      var btn = await waitForSelectors(clickSelectors, 8000);",
    "      btn.click();",
    "      return { ok: true };",
    "    } catch (e) {}",
    "  }",
    "  pressEnter(input);",
    "  await sleep(400);",
    "  var sendBtn = findBySelectors(['button[data-testid*=\"send\"]', 'button[aria-label=\"发送消息\"]', 'button[aria-label*=\"发送\"]', '.send-button-container'].concat(clickSelectors));",
    "  if (sendBtn) { sendBtn.click(); }",
    "  return { ok: true };",
    "})()",
  ].join("\n");
}

export function buildVerifyDispatchedScript(
  channel: ChannelDefinition,
  prompt: string,
): string {
  const channelJson = JSON.stringify(channel);
  return [
    "(function () {",
    `  var channel = ${channelJson};`,
    `  var prompt = ${JSON.stringify(prompt)};`,
    "  var expected = (prompt || '').trim();",
    "  function isVisible(el) {",
    "    if (!el || !el.getClientRects().length) return false;",
    "    var style = window.getComputedStyle(el);",
    "    return style.visibility !== 'hidden' && style.display !== 'none';",
    "  }",
    "  function findInput() {",
    "    for (var i = 0; i < channel.fill.selectors.length; i++) {",
    "      var nodes;",
    "      try { nodes = document.querySelectorAll(channel.fill.selectors[i]); } catch (e) { continue; }",
    "      for (var j = 0; j < nodes.length; j++) {",
    "        var node = nodes[j];",
    "        if (!(node instanceof HTMLElement) || !isVisible(node)) continue;",
    "        return node;",
    "      }",
    "    }",
    "    return null;",
    "  }",
    "  function looksSubmitted(inputEl) {",
    "    if (!inputEl || !expected) return false;",
    "    if (inputEl instanceof HTMLTextAreaElement || inputEl instanceof HTMLInputElement) {",
    "      var v = (inputEl.value || '').trim();",
    "      return v.length === 0 || v !== expected;",
    "    }",
    "    if (inputEl.isContentEditable || inputEl.getAttribute('contenteditable') === 'true') {",
    "      var t = (inputEl.innerText || inputEl.textContent || '').trim();",
    "      return t.length === 0 || t !== expected;",
    "    }",
    "    return false;",
    "  }",
    "  return { ok: looksSubmitted(findInput()) };",
    "})()",
  ].join("\n");
}

export function buildResetClickScript(channel: ChannelDefinition): string {
  const cfg = channel.sessionReset.click;
  if (!cfg) return "(() => ({ ok: false, error: 'no click reset' }))()";
  // 重置场景：入口页已加载，按钮找不到就尽快放弃，避免整批卡在 0/N
  const waitMs = Math.min(cfg.waitMs ?? 5000, 5000);
  const lines = [
    "(async function () {",
    `  var cfg = ${JSON.stringify({ selectors: cfg.selectors, waitMs })};`,
    "  function isVisible(el) {",
    "    var style = window.getComputedStyle(el);",
    "    return style.visibility !== 'hidden' && style.display !== 'none';",
    "  }",
    "  function findBySelectors(selectors) {",
    "    for (var i = 0; i < selectors.length; i++) {",
    "      var nodes;",
    "      try { nodes = document.querySelectorAll(selectors[i]); } catch (e) { continue; }",
    "      for (var j = 0; j < nodes.length; j++) {",
    "        var node = nodes[j];",
    "        if (!(node instanceof HTMLElement)) continue;",
    "        if (!isVisible(node)) continue;",
    "        return node;",
    "      }",
    "    }",
    "    return null;",
    "  }",
    "  function waitForSelectors(selectors, maxMs) {",
    "    var max = maxMs || 5000;",
    "    var start = Date.now();",
    "    return new Promise(function (resolve, reject) {",
    "      var obs = new MutationObserver(tryOnce);",
    "      function tryOnce() {",
    "        var t = findBySelectors(selectors);",
    "        if (t) { obs.disconnect(); resolve(t); return; }",
    "        if (Date.now() - start >= max) { obs.disconnect(); reject(new Error('timeout waiting for reset control')); }",
    "      }",
    "      obs.observe(document.documentElement, { childList: true, subtree: true, attributes: true });",
    "      tryOnce();",
    "    });",
    "  }",
    "  var btn = await waitForSelectors(cfg.selectors, cfg.waitMs || 5000);",
    "  btn.click();",
    "  return { ok: true };",
    "})()",
  ];
  return lines.join("\n");
}
